---
- name: Create ECR Secret on Kubernetes Master
  hosts: k8s_nodes
  become: yes
  tasks:
    - name: Execute kubectl command
      shell: |
        kubectl create secret docker-registry ecr-secret \
          --docker-server=381491857320.dkr.ecr.us-east-1.amazonaws.com \
          --docker-username=AWS \
          --docker-password=$(aws ecr get-login-password --region us-east-1) \
          --docker-email=your-email@example.com
      
