apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
      - name: python-app
        image: 381491857320.dkr.ecr.us-east-1.amazonaws.com/k8s-app-repo:latest
        ports:
        - containerPort: 3000
        env:
          - name: MYSQL_USERNAME
            value: "root"  # Set this to your MySQL username
          - name: MYSQL_PASSWORD
            value: "rootpassword"  # Set this to your MySQL password
          - name: MYSQL_INSTANCE_NAME
            value: "mydb"  # Set this to your MySQL database name
          - name: MYSQL_PORT_3306_TCP_ADDR
            value: "db"  # Set this to the hostname or service name of MySQL
          - name: MYSQL_PORT_3306_TCP_PORT
            value: "3306"  # Ensure this matches the port your MySQL service is using
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
